
```{r}
library(tidyverse)
library(readr)
```

```{r}
get_diff_data <- function(path, lab_name, crnt_filter="All") {
  data <- readr::read_delim(path)
  # rename all mlogloss occurances to logloss
  data <- data %>% dplyr::mutate(
              MODEL_1 = str_replace(MODEL_1, "mlogloss", "logloss"),
              MODEL_2 = str_replace(MODEL_2, "mlogloss", "logloss")
  )
  data %>% filter(SET == "Test", FILTER==crnt_filter)
  data <-  data %>% filter(SET=="Test", FILTER==crnt_filter)

  data <- data %>% dplyr::mutate(
              MODEL_2 = case_when(
                  ((MODEL_2 == "lr_logloss_0_base") & (lab_name != "TSH")) | ((MODEL_2 == "xgb_logloss_1_clinpheno") & (lab_name == "TSH")) ~ "baseline",
                  MODEL_2 == "xgb_logloss_3_registry" ~ "registry data",
                  MODEL_2 == "xgb_logloss_3_otherlabs" ~ "other labs",
                  #MODEL_2 == "xgb_logloss_2_lastval" ~ "last value",
                  MODEL_2 == "xgb_logloss_2_sumstats" ~ "sumstats",
                  MODEL_2 == "xgb_logloss_4_all" ~ "all data",
                  MODEL_2 == "xgb_logloss_5_all_pgs" ~ "all data + PGS",
                  MODEL_2 == "maxim" ~ "maxim"
              )
  )
  data <- data %>% dplyr::mutate(
              MODEL_1 = case_when(
                  ((MODEL_1 == "lr_logloss_0_base") & (lab_name != "TSH")) | ((MODEL_1 == "xgb_logloss_1_clinpheno") & (lab_name == "TSH")) ~ "baseline",
                  MODEL_1 == "xgb_logloss_3_registry" ~ "registry data",
                  MODEL_1 == "xgb_logloss_3_otherlabs" ~ "other labs",
                  #MODEL_1 == "xgb_logloss_2_lastval" ~ "last value",
                  MODEL_1 == "xgb_logloss_2_sumstats" ~ "sumstats",
                  MODEL_1 == "xgb_logloss_4_all" ~ "all data",
                  MODEL_1 == "xgb_logloss_5_all_pgs" ~ "all data + PGS",
                  MODEL_1 == "maxim" ~ "maxim"
              )
  )
  data <- dplyr::rename(
              data,
              Predictors = MODEL_2
  )
  data <- data %>% filter(((TRAIN_1 == "y_NEXT_ABNORM") & (TRAIN_2 == "y_NEXT_ABNORM") & (EVAL == "y_NEXT_ABNORM") & (lab_name != "eGFR")) |
                           ((TRAIN_1 == "y_MEAN_ABNORM") & (TRAIN_2 == "y_MEAN_ABNORM") & (EVAL == "y_NEXT_ABNORM") & (lab_name == "eGFR")))
  # help me Filter out NAs
  data <- data %>% filter(!is.na(MODEL_1), !is.na(Predictors))

  # If est < 0 then switch ci_neg and ci_pos
  data <- data %>% mutate(
      AUCDiff_CIneg_new = ifelse(AUCDiff_Est < 0, AUCDiff_CIpos, AUCDiff_CIneg),
      AUCDiff_CIpos_new = ifelse(AUCDiff_Est < 0, AUCDiff_CIneg, AUCDiff_CIpos)
  )
  data$AUCDiff_CIneg <- data$AUCDiff_CIneg_new
  data$AUCDiff_CIpos <- data$AUCDiff_CIpos_new
  data$Lab_name <- lab_name

  if (nrow(data %>% filter(Predictors == "all data + PGS")) == 0) {
    all_data_rows <- data %>% filter(MODEL_1 == "baseline", Predictors == "all data")
    all_data_pgs_rows <- all_data_rows %>% mutate(Predictors = "all data + PGS")
    data <- rbind(data, all_data_pgs_rows)
    data <- data %>% unique()
  }
  # if xgb_logloss_5_all_pgs not there replace with xgb_logloss_4_all
  if (nrow(data %>% filter(Predictors == "maxim")) == 0) {
    all_data_rows <- data %>% filter(MODEL_1 == "baseline", Predictors == "all data")
    all_data_pgs_rows <- all_data_rows %>% mutate(Predictors = "maxim")
    data <- rbind(data, all_data_pgs_rows)
    data <- data %>% unique()
  }

  return(data)
}
```


```{r}
test_data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/egfr_testv10_2022_w3_diffs_2025-10-20.csv")

for(filter in unique(test_data$FILTER)) {
  data <- auc_diff_comps(filter, "baseline", 0.05)
  plt <- plot_data(data, alpha_sign=TRUE)
  plt
  #ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/auc_diffs_", tolower(gsub(" ", "_", filter)), ".png"), plot = plt, width = 17, height = 10, dpi = 300, bg = "white")
  #ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/auc_diffs_", tolower(gsub(" ", "_", filter)), ".pdf"), plot = plt, width = 17, height = 10, dpi = 300, bg = "white")

}

for(filter in unique(test_data$FILTER)) {
  data <- auc_diff_comps(filter, "baseline", 0.05)
  plt <- plot_data(data, alpha_sign=FALSE)
  plt
  #ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/auc_diffs_", tolower(gsub(" ", "_", filter)), "_nosignmark.png"), plot = plt, width = 17, height = 8, dpi = 300, bg = "white")
  #ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/auc_diffs_", tolower(gsub(" ", "_", filter)), "_nosignmark.pdf"), plot = plt, width = 17, height = 8, dpi = 300, bg = "white")

}
```

```{r}
crnt_filter <- "No history"
baseline_model <- "baseline"
sig_alpha = 0.05

get_lab_increase_pvals <- function(data, lab_name) {
  pvals <- c()
  for (i in seq_along(levels(data$Predictors))) {
    if (i < length(levels(data$Predictors))) {
      two_levels <- levels(data$Predictors)[i:(i+1)]
      print(two_levels)
      # do whatever you want with subset_data
      if (nrow(data %>% filter(Lab_name == lab_name, MODEL_1 == two_levels[1], Predictors == two_levels[2])) > 0) {
        pval <- (data %>% filter(Lab_name == lab_name, 
                                 MODEL_1 == two_levels[1], 
                                 Predictors == two_levels[2]))$AUCDiff_Pvalue
        print(two_levels)
        if (data %>% filter(Lab_name == lab_name, MODEL_1 == two_levels[1], Predictors == two_levels[2]) %>% nrow() == 0) {
          pval <- 1
        }
        print(pval)
      } else {
        print(two_levels)

        pval <- (data %>% filter(Lab_name == lab_name, 
                                 Predictors == two_levels[1], 
                                 MODEL_1 == two_levels[2]))$AUCDiff_Pvalue
        if (data %>% filter(Lab_name == lab_name, Predictors == two_levels[1], MODEL_1 == two_levels[2]) %>% nrow() == 0) {
          pval <- 1
        }
        print(pval)
      }
      pvals <- c(pvals, pval)
    }
  }
  return(pvals)
}


auc_diff_comps <- function(crnt_filter,
                           baseline_model,
                           sig_alpha=0.05/4) {
  data_egfr <- get_diff_data("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/egfr_testv10_2022_w3_diffs_2025-10-20.csv",
                              "eGFR",
                              crnt_filter)
  data_hba1c <- get_diff_data("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/hba1c_testv5_2022_w3_diffs_2025-10-17.csv",
                              "HbA1c",
                              crnt_filter)
  data_tsh <- get_diff_data("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/tsh_testv3_2022_w3_diffs_2025-10-20.csv",
                              "TSH",
                              crnt_filter)
  data_ldl <- get_diff_data("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/ldl_testv3_2022_w3_diffs_2025-10-20.csv",
                              "LDL",
                              crnt_filter)
  data <- rbind(data_egfr, data_hba1c, data_tsh, data_ldl) %>% filter(!is.na(Predictors))
  data$Metric <- "AUC"

  data <- data %>% select(Lab_name, Metric, MODEL_1, Predictors, AUCDiff_Pvalue, AUCDiff_Est, AUCDiff_CIneg, AUCDiff_CIpos)
  # add row zero for clinpheno
  data <- data %>% 
    bind_rows(tibble(Lab_name = unique(data$Lab_name),
                     MODEL_1 = baseline_model,
                     Predictors = baseline_model,
                     AUCDiff_Est = 0,
                     AUCDiff_CIneg = 0,
                     AUCDiff_CIpos = 0,
                     #AUCDiff_sign = "s",
                     #AUCDiff_Pvalue = 0,
                     Metric = "AUC")) %>%
    arrange(Lab_name, Predictors)

  data$Predictors <- factor(data$Predictors, 
                              levels = c("baseline", "registry data", "other labs", "last value", "sumstats", "all data", "all data + PGS", "maxim"))

  # want the model_1 and model_2 each two models in order of predictor levels
  pvals_egfr <- get_lab_increase_pvals(data, "eGFR")
  pvals_hba1c <- get_lab_increase_pvals(data, "HbA1c")
  pvals_tsh <- get_lab_increase_pvals(data, "TSH")
  pvals_ldl <- get_lab_increase_pvals(data, "LDL")

  pvals <- tibble(
    Lab_name = c(rep("eGFR", length(pvals_egfr)+1), 
                rep("HbA1c", length(pvals_hba1c)+1), 
                rep("TSH", length(pvals_tsh)+1), 
                rep("LDL", length(pvals_ldl)+1)),
    Predictors = rep(c("baseline", "registry data", "other labs", "last value", "sumstats", "all", "all data + PGS", "maxim"), 4),
    AUCDiff_Pvalue = c(c(0, pvals_egfr), c(0, pvals_hba1c), c(0, pvals_tsh), c(0, pvals_ldl))
  )
  pvals <- pvals %>% mutate(AUCDiff_sign = ifelse(AUCDiff_Pvalue < sig_alpha, "sig", "ns"))
  data <- left_join(data, pvals, by = c("Lab_name", "Predictors"))
  data %>% filter(Predictors=="sumstats")

  data <- data %>% filter(MODEL_1 == baseline_model)

  point_data <- data %>% 
    group_by(Predictors) %>% 
    summarize(AUCDiff_Est_MEAN = mean(AUCDiff_Est, na.rm = TRUE),
              AUCDiff_Est_SD = sd(AUCDiff_Est, na.rm = TRUE)) 
  data <- left_join(data, point_data, by = c("Predictors"))
  data$Predictors <- factor(data$Predictors, 
                              levels = c("baseline", "registry data", "other labs", "last value", "sumstats", "all data", "all data + PGS", "maxim"))
  data <- data %>% arrange(Predictors)

  return(data)
}

plot_data <- function(data, alpha_sign=TRUE) {

  if (alpha_sign) {
    plt <- ggplot(data, aes(x = Predictors, y = AUCDiff_Est, fill = Lab_name, alpha=AUCDiff_sign)) 
  } else {
    plt <- ggplot(data, aes(x = Predictors, y = AUCDiff_Est, fill = Lab_name) )
  }
  plt + geom_bar(stat = "identity", position = position_dodge(0.9)) +
    scale_alpha_manual(values = c("sig" = 1, "ns" = 0.5), guide="none") +
    geom_errorbar(aes(ymin = AUCDiff_Est,
                      ymax = AUCDiff_CIpos,
                      color = Lab_name), 
                  position = position_dodge(0.9),
                  width = 0.2,
                  linewidth=1.5) +
    geom_point(aes(x=Predictors, y=AUCDiff_Est_MEAN), size=7, show.legend=FALSE) +
    geom_path(aes(x=Predictors, y=AUCDiff_Est_MEAN, group=Lab_name), size=1.5) +
    # facet with three rows
    facet_wrap(~ Metric, nrow=3, scales = "free_y") +
    labs(title = "",
          x = "",
          y = "AUC difference compared to baseline") +
    scale_fill_manual(values = custom_colors_brewer_sorted(5)[c(1, 2, 3, 5)]) +
    scale_color_manual(values = custom_colors_brewer_sorted(5)[c(1, 2, 3, 5)], guide="none") +
    theme_custom(base_size=32) +
    theme(strip.text=ggplot2::element_blank())
}

```


```{r}
egfr_importances <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/egfr_xgb_logloss_5_all_pgs_y_NEXT_ABNORM_shap_importance_test_2025-10-15.csv", delim=",") %>% mutate(Lab_name="eGFR")
egfr_importances <- egfr_importances %>% mutate(N=row_number()) %>% filter(N %in% c(1, 4, 5, 6, 7, 8, 11, 13, 14, 16))

hba1c_importances <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/hba1c_xgb_logloss_5_all_pgs_y_NEXT_ABNORM_shap_importance_test_2025-10-17.csv", delim=",") %>% mutate(Lab_name="HbA1c")
hba1c_importances <- hba1c_importances %>% mutate(N=row_number()) %>% filter(N %in% c(1, 3, 5, 7, 8, 9, 12, 13, 14, 16))

ldl_importances <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/ldl_xgb_logloss_5_all_pgs_y_NEXT_ABNORM_shap_importance_test_2025-10-17.csv", delim=",") %>% mutate(Lab_name="LDL")
ldl_importances <- ldl_importances %>% mutate(N=row_number()) %>% filter(N %in% c(1, 2, 6, 7, 8, 10, 11, 13, 15, 16))

tsh_importances <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/tsh_xgb_mlogloss_4_all_y_NEXT_ABNORM_shap_importance_test_2025-10-14.csv", delim=",") %>% mutate(Lab_name="TSH")
tsh_importances <- tsh_importances %>% select(field_1, labels, Lab_name) %>% rename(mean_shap = field_1)
tsh_importances <- tsh_importances %>% arrange(desc(mean_shap)) %>% mutate(N=row_number()) %>% filter(N %in% c(1, 5, 6, 8, 9, 10, 12, 13, 14, 15))

importances <- rbind(egfr_importances, hba1c_importances, ldl_importances, tsh_importances)
importances$Lab_name <- factor(importances$Lab_name, levels = c("eGFR", "HbA1c", "LDL", "TSH"))
importances <- importances %>% arrange(Lab_name, desc(mean_shap)) %>% mutate(ORDER=row_number())

name_mapping <- c(
  "C08CA" = "Dihydropyridine derivatives (C08CA)",
  "C07AB" = "Selective beta blockers (C07AB)",
  "I10" = "Hypertension (I10)",
  "Mean - Erythrocyte sedimentation rate by Westergren method" = "ESR by Westergren method",
  "Mean - Fasting glucose  in Serum or Plasma" = "Fasting glucose",
  "C09AA" = "ACE inhibitors (C09AA)",
  "Mean - Hemoglobin  in Blood" = "Hemoglobin",
  "Mean - Fasting Glucose" = "Fasting glucose",
  "Mean - Triglyceride  in Serum or Plasma --fasting" = "fasting TG",
  "Mean - Alanine aminotransferase  in Serum or Plasma" = "ALT",
  "Mean - Leukocytes  in Blood" = "Leukocytes",
  "Mean - eGFR  in Serum, Plasma or Blood by CKD-EPI" = "eGFR",
  "Mean - Cholesterol in HDL  in Serum or Plasma" = "HDL",
  "Mean - Gamma glutamyl transferase  in Serum or Plasma"= "GGT",
  "Mean - Glucose  in Serum or Plasma" = "Glucose",
  "Mean - Hematocrit  of Blood" = "Hematocrit",
  "Mean - Albumin  in Serum or Plasma" = "Albumin",
  "Mean - Aspartate aminotransferase  in Serum or Plasma" = "AST",
  "Mean - Cholesterol  in Serum or Plasma" = "Total cholesterol",
  "Mean - MCH" = "MCH",
  "Mean - Erythrocytes  in Blood" = "Erythrocytes",
  "Mean - MCHC" = "MCHC",
  "Mean - MCHC " = "MCHC",
  "A03FA" = "Propulsives (A03FA)",
  "Mean - MCV " = "MCV",
  "Z36" = "Antenatal screening (Z36)",
  "Mean - Monocytes  in Blood" = "Monocytes",
  "M03BC" =  "Muscle relaxants (M03BC)",
  "R06AX" = "Antihistamines (R06AX)",
  "Mean - t4"= "Free T4",
  "Mean - Calcium  in Serum or Plasma" = "Calcium",
  "M75" = "Shoulder lesions (M75)",
  "Z71" = "Healthcare encounter (Z71)",
  "O80" = "Uncomplicated delivery (O80)",
  "R01AD" = "Nasal corticosteroids (R01AD)",
  "PGS1" = "PGS",
  "E11" = "Type-2 diabetes (E11)",
  "Mean - ftri" = "Free TG",
  "N06AB" = "SSRIs (N06AB)",
  "Mean - C reactive protein  in Serum or Plasma" = "CRP",
  "M01AH" = "Coxibs (M01AH)"
)
importances %>% filter(Lab_name == "TSH")

# add the N to the labels 

importances <- importances %>% mutate(labels = recode(labels, !!!name_mapping))
importances <- importances %>% mutate(labels = paste0(N, " - ", labels))
print(importances, n=40)
```

```{r, width=20}
reorder_within <- function(x, by, within, fun = mean, sep = "___") {
  x <- paste(x, within, sep = sep)
  stats::reorder(x, by, FUN = fun)
}
scale_y_reordered <- function(sep = "___") {
  ggplot2::scale_y_discrete(labels = function(x) sub(paste0(sep, ".*$"), "", x))
}

panel_b <- ggplot(importances, aes(x=mean_shap, y=reorder_within(labels, mean_shap, Lab_name), fill=Lab_name)) +
  geom_bar(stat="identity") +
  facet_wrap(~Lab_name, scales = "free", nrow=1) +
  scale_y_reordered() + 
  theme_custom(base_size=32) +
  labs(x="mean(|shap values|)", y="", caption="") +
  scale_fill_manual(values = custom_colors_brewer_sorted(5)[c(1, 2, 3, 5)], guide="none") +
  theme(panel.grid.major.y = ggplot2::element_blank(),
        panel.grid.major.x=ggplot2::element_line(colour="grey75", linewidth=1.5-0.5*1.5, linetype=2),
        strip.text = element_blank()) +
  scale_x_continuous(labels = scales::label_number(accuracy = 0.1), breaks=c(0, 0.2, 0.4))
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/importances.pdf"), width=30, height=10, dpi=300, bg="white")

```

```{r}
hba1c_aucs <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/hba1c_testv5_2022_w3_aucs_2025-10-20.csv") %>% mutate(Lab_name="HbA1c", Position=2)
egfr_aucs <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/egfr_testv10_2022_w3_aucs_2025-10-20.csv") %>% mutate(Lab_name="eGFR", Position=1)
tsh_aucs <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/tsh_testv3_2022_w3_aucs_2025-10-20.csv") %>% mutate(Lab_name="TSH", Position=3)
ldl_aucs <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/down/down_valid_2025-10-20/csv/ldl_testv3_2022_w3_aucs_2025-10-20.csv") %>% mutate(Lab_name="LDL", Position=4)

aucs <- rbind(hba1c_aucs %>% select(colnames(tsh_aucs)), egfr_aucs %>% select(colnames(tsh_aucs)), tsh_aucs, ldl_aucs %>% select(colnames(tsh_aucs)))

aucs <- aucs %>% filter(FILTER=="All", SET=="Test", `Eval goal`=="y_NEXT_ABNORM", `Train Goal` == "y_NEXT_ABNORM", (Predictors=="5_all_pgs"&Lab_name!="TSH")| (Predictors=="mlogloss_4_all"&Lab_name=="TSH"))
# have one column for AUC and Averageprecision with CI pos and neg extra columns
# where is the average precision?
aucs_1 <- aucs %>% select(Lab_name, Position, AUC, AUC_CIneg, AUC_CIpos) %>% mutate(AUC_type="AUC")
aucs_2 <- aucs %>% select(Lab_name, Position, avgPrec, avgPrec_CIneg, avgPrec_CIpos) %>%
  rename(AUC = avgPrec,
         AUC_CIneg = avgPrec_CIneg,
         AUC_CIpos = avgPrec_CIpos) %>% mutate(AUC_type="Average Precision")
aucs <- rbind(aucs_1, aucs_2)

ggplot(aucs, aes(x=Position, y=AUC, color=Lab_name)) +
  geom_point(size=7) +
  # not errorbar but line arrange?
  geom_line(aes(ymin=AUC_CIneg, ymax=AUC_CIpos), position=position_dodge(0.9), width=0.2, linewidth=1.5) +
  geom_linerange(aes(ymin=AUC_CIneg, ymax=AUC_CIpos), position=position_dodge(0.9), width=0.2, linewidth=1.5) +
  labs(x="", y="") +
  facet_wrap(~AUC_type, nrow=1, scales="free") +
  scale_y_continuous(labels = scales::label_number(accuracy = 0.01), breaks=seq(0.1, 1, by=0.05)) +
  scale_color_manual(values = custom_colors_brewer_sorted(5)[c(1, 2, 3, 5)]) +
  theme_custom(base_size=32) +
  theme(strip.text=element_blank())

ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs.pdf"), width=7, height=10, dpi=300, bg="white")

```

```{r}
data <- auc_diff_comps(filter, "baseline", 1)
panel_a <- plot_data(data, alpha_sign=FALSE)
  
```

```{r}
library(cowplot)
top_panel <- cowplot::plot_grid(NULL, panel_a, NULL, nrow=1, rel_widths=c(0.2, 0.6, 0.2))
cowplot::plot_grid(top_panel, panel_b, ncol=1, nrow=2)
```

```{r}
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/v1_fig2_v3.png"), width=30, height=20, dpi=300, bg="white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/v1_fig2_v3.pdf"), width=35, height=20, dpi=300, bg="white")
```

```{r}
library(cowplot)
top_panel <- cowplot::plot_grid(NULL, panel_a, NULL, nrow=1, rel_widths=c(0.2, 0.6, 0.2))
cowplot::plot_grid(top_panel, panel_b, ncol=1, nrow=2)
```

```{r}
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/v1_fig2_v2.png"), width=30, height=20, dpi=300, bg="white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/v1_fig2_v2.pdf"), width=35, height=20, dpi=300, bg="white")

```


```{r}
so_formatter <- function(x) {
  dplyr::case_when(
      x < 1e3 ~ as.character(x),
      x < 1e6 ~ paste0(as.character(x/1e3), "K"),
      x < 1e9 ~ paste0(as.character(x/1e6), "M"),
      TRUE ~ "To be implemented..."
  )
}


#' Custom color selection 
#' 
#' Based on https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=10
#' 
#' @param N_colors The number of colors
#' 
#' @author Kira E. Detrois
#' 
#' @export 
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c( "#29557B",   "#748AAA",   "#7D7C7F", "#CCB6AF", "#588986", "#D5694F","#7BA05B","#FBCF9D", "#EAB034",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}
##################### THEMES ####################
theme_custom <- function(base_size = 18,
                      legend_pos = "bottom",
                      plot_top_margin = -30,
                      axis_x_bottom_margin=0,
                      axis_y_left_margin=0,
                      legend_box_spacing=1,
                      line_size=1.5) {
    ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      text=ggplot2::element_text(colour="black", family="sans"),
      # Titles
      plot.title=ggplot2::element_text(hjust=0, margin=margin(t=plot_top_margin, b=5), size=base_size),
      plot.subtitle=ggplot2::element_text(hjust=0, size=base_size*0.9,  margin=margin(t=plot_top_margin, b=5), face="bold"),
      plot.caption=ggplot2::element_text(size=base_size*0.6, hjust=0, margin=margin(t=10)),
      # Facet grid / wrap titles
      strip.text = ggplot2::element_text(hjust=0, face="bold", size=base_size*0.8, margin=margin(b=5)),
      # Legend
      legend.title=ggplot2::element_blank(),
      legend.position = legend_pos,
      legend.text=ggplot2::element_text(size=base_size*0.8),
      legend.key.spacing.y=grid::unit(0.5, "lines"),
      legend.margin = ggplot2::margin(legend_box_spacing, legend_box_spacing, legend_box_spacing, legend_box_spacing),
      # Axes
      axis.title=ggplot2::element_text(size=base_size*0.8),
      axis.text = ggplot2::element_text(size=base_size*0.75),
      axis.title.x = ggplot2::element_text(margin=margin(t=5, b=axis_x_bottom_margin)),
      axis.title.y = ggplot2::element_text(margin=margin(r=5), l=axis_y_left_margin, angle=90),
      # Other settings
      panel.border = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(colour=NA, fill=NA),
      # Grid settings
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_line(colour="grey75", linewidth=line_size-0.5*line_size, linetype=2),
      panel.grid.minor.y = ggplot2::element_blank(),
    )
}

```
