```{r}
library(tidyverse)
library(dplyr)
```

```{r}
tsh_high_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/tsh_stats_2024-10-18.csv") %>% filter(ABNORM_TYPE == 1) 
tsh_low_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/tsh_stats_2024-10-18.csv") %>% filter(ABNORM_TYPE == -1)
hba1c_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/hba1c_stats_2024-10-18.csv")
egfr_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/egfr_stats_2024-10-18.csv")
fgluk_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/fgluk_stats_2024-10-18.csv")

stats <- bind_rows(tsh_high_stats %>% dplyr::mutate(LAB="TSH high"), 
                   tsh_low_stats %>% dplyr::mutate(LAB="TSH low"),
                   hba1c_stats %>% dplyr::mutate(LAB="HbA1c"), 
                   fgluk_stats %>% dplyr::mutate(LAB="Fasting glucose"),
                   egfr_stats %>% dplyr::mutate(LAB="eGFR"))
stats
```

```{r}
plt_data <- stats %>% 
                dplyr::filter(STEP %in% c("N", "A", "N→A","N→A(+D)", "A2023(+D)")) %>% 
                dplyr::filter(ABNORM_DEF == "CUSTOM", DIAG_TYPE == "DIAG+DATA" | is.na(DIAG_TYPE)) %>%
                dplyr::mutate(STEP=factor(STEP, levels= c("N", "A", "N→A", "N→A(+D)", "A2023(+D)")))
ggplot(plt_data, aes(x=STEP, y=N_INDV, fill=SUBSET)) +
    geom_col(position="identity", width=0.5) +
    theme_custom(plot_top_margin=0) +
    scale_fill_manual(values=custom_colors_brewer(3)) +
    facet_wrap(~LAB) +
    scale_y_continuous(labels=function(x){so_formatter(x)}) +
     labs(y="Number of individuals", x="", fill="") #+
    # scale_x_discrete(labels=c("N", "A", "N->A", "N->A(+D)", "A2023(+D)"))

#ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/norm_to_abnorm_counts_2024-10-07.pdf", width=20, height=6)
```


```{r}
tsh_ca_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/tsh_stats_2024-10-07.csv")
hba1c_ca_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/hba1c_ca_stats_2024-10-07.csv")
egfr_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/egfr_stats_2024-10-07.csv")

stats <- bind_rows(tsh_ca_stats %>% dplyr::mutate(LAB="TSH"), hba1c_ca_stats %>% dplyr::mutate(LAB="HbA1c"), egfr_stats %>% dplyr::mutate(LAB="eGFR"))
stats
```

```{r}
plt_data <- stats %>% 
                dplyr::filter(STEP %in% c("Normal", "Abnormal", "Abnorm after norm", "Abnorm + No diag before", "First abnormal 2023 + No diag before")) %>% 
                dplyr::mutate(STEP=factor(STEP, levels= c("Normal", "Abnormal", "Abnorm after norm", "Abnorm + No diag before", "First abnormal 2023 + No diag before")))
ggplot(plt_data, aes(x=STEP, y=N_INDV, fill=SET)) +
    geom_col(position="identity", width=0.5) +
    theme_custom(plot_top_margin=0) +
    scale_fill_manual(values=custom_colors_brewer(3)) +
    facet_wrap(~LAB) +
    scale_y_continuous(labels=function(x){so_formatter(x)}) +
    labs(y="Number of individuals", x="", fill="") +
    scale_x_discrete(labels=c("N", "A", "N->A", "N->A(+D)", "N->A2023(+D)"))

ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/norm_to_abnorm_counts_ca_2024-10-11.pdf", width=20, height=6)
```

```{r}
plt_data <- stats %>% 
                dplyr::filter(STEP %in% c("Abnorm after norm", "Abnorm + No diag before", "First abnormal 2023 + No diag before")) %>% 
                dplyr::mutate(STEP=factor(STEP, levels= c("Abnorm after norm", "Abnorm + No diag before", "First abnormal 2023 + No diag before")))
ggplot(plt_data, aes(x=STEP, y=N_INDV, fill=SET)) +
    geom_col(position="identity", width=0.5) +
    theme_custom(plot_top_margin=0) +
    scale_fill_manual(values=custom_colors_brewer(3)) +
    facet_wrap(~LAB, scales="free") +
    scale_y_continuous(labels=function(x){so_formatter(x)}) +
    labs(y="Number of individuals", x="", fill="") +
    scale_x_discrete(labels=c("N->A", "N->A(+D)", "N->A2023(+D)"))
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/norm_to_abnorm_counts_zoom_ca_2024-10-11.pdf", width=12, height=4, bg="white")
```

```{r}
box_stats <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2024-10/box_lens_stats_2024-10-10.csv")
box_stats %>% pivot_wider(names_from=STAT, values_from=VALUE)

ggplot(box_stats %>% 
          pivot_wider(names_from=STAT, values_from=VALUE) %>%
          mutate(ABNORMAL=factor(case_when(ABNORMAL == 0 ~ "Normal", ABNORMAL == 1 ~ "High", ABNORMAL == -1 ~ "Low"), levels=c("Normal", "High", "Low"))), 
       aes(x=1, fill=LAB)) +
  geom_boxplot(aes(group=LAB, ymin=y0, lower=y25, middle=y50, upper=y75, ymax=y100), 
                   stat="identity",
                   position=position_dodge2(width=0.75, preserve="single")) +
  theme_custom(plot_top_margin=0, legend_pos="bottom") +
  labs(x="", y="Years", title="Length of first continuous period in years") +
  theme(axis.ticks.x=element_blank(), axis.text.x=element_blank(), panel.grid.minor.y=element_blank()) +
  facet_wrap(~ABNORMAL) +
  scale_fill_manual(values=c(custom_colors_brewer(4)[1], custom_colors_brewer(4)[3], custom_colors_brewer(4)[2], custom_colors_brewer(4)[4])) +
  scale_y_continuous(breaks=c(0, 365.25, 365.25*2, 365.25*3, 365.25*4, 365.25*5, 365.25*6, 365.25*7, 365.25*8), labels=function(x){round(x/365.25)}) 
#ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/abnorml_length_boxplots_2024-10-10.pdf", width=7, height=9)

```

```{r}
so_formatter <- function(x) {
  dplyr::case_when(
      x < 1e3 ~ as.character(x),
      x < 1e6 ~ paste0(as.character(x/1e3), "K"),
      x < 1e9 ~ paste0(as.character(x/1e6), "M"),
      TRUE ~ "To be implemented..."
  )
}


#' Custom color selection 
#' 
#' Based on https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=10
#' 
#' @param N_colors The number of colors
#' 
#' @author Kira E. Detrois
#' 
#' @export 
custom_colors_brewer <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF", "#841C26", "#7D7C7F", "#FBCF9D",  "#7BA05B", "#588986")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}
##################### THEMES ####################
theme_custom <- function(base_size = 18,
                      legend_pos = "bottom",
                      plot_top_margin = -30,
                      axis_x_bottom_margin=0,
                      axis_y_left_margin=0,
                      legend_box_spacing=1,
                      line_size=1.5) {
    ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      text=ggplot2::element_text(colour="black"),
      # Titles
      plot.title=ggplot2::element_text(hjust=0, margin=margin(t=plot_top_margin, b=5), size=base_size),
      plot.subtitle=ggplot2::element_text(hjust=0, size=base_size*0.9,  margin=margin(t=plot_top_margin, b=5), face="bold"),
      plot.caption=ggplot2::element_text(size=base_size*0.6, hjust=0, margin=margin(t=10)),
      # Facet grid / wrap titles
      strip.text = ggplot2::element_text(hjust=0, face="bold", size=base_size*0.8, margin=margin(b=5)),
      # Legend
      legend.title=ggplot2::element_blank(),
      legend.position = legend_pos,
      legend.text=ggplot2::element_text(size=base_size*0.8),
      legend.key.spacing.y=grid::unit(0.5, "lines"),
      legend.margin = ggplot2::margin(legend_box_spacing, legend_box_spacing, legend_box_spacing, legend_box_spacing),
      # Axes
      axis.title=ggplot2::element_text(size=base_size*0.8),
      axis.text = ggplot2::element_text(size=base_size*0.75),
      axis.title.x = ggplot2::element_text(margin=margin(t=5, b=axis_x_bottom_margin)),
      axis.title.y = ggplot2::element_text(margin=margin(r=5), l=axis_y_left_margin, angle=90),
      # Other settings
      panel.border = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(colour=NA, fill=NA),
      # Grid settings
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_line(colour="black", linewidth=line_size-0.5*line_size, linetype=2),
      panel.grid.minor.y = ggplot2::element_line(colour = "black", linewidth=line_size-0.75*line_size, linetype=2),
    )
}

```
