```{r}
library(tidyverse)
```

```{r}
data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_year_counts.csv")
data
```

```{r}
library(cowplot)
n <- ggplot(data %>% dplyr::filter(ICD_AFTER==1), aes(x=YEAR, y=N_CASE)) +
    geom_line(size=1, aes(color=as.factor(EXCLUDE))) +
    facet_wrap(~DIFF) +
    scale_color_manual(values=custom_colors_brewer_sorted(2), labels=c("No extra exclusions", "Exclude prior cancer+kidney")) +
    # remove legend entirely
    theme_custom(plot_top_margin=0, base_size=22) +
    theme(legend.position = "none") +
    scale_y_continuous(labels=so_formatter) +
    labs(x="Year", y="Number of cases")
n

pct <- ggplot(data %>% dplyr::filter(ICD_AFTER==1), aes(x=YEAR, y=(N_CASE/(N_CASE+N_CONTROL)))) +
    geom_line(size=1, aes(color=as.factor(EXCLUDE))) +
    facet_wrap(~DIFF) +
    scale_color_manual(values=custom_colors_brewer_sorted(2), labels=c("No extra exclusions", "Exclude prior cancer + other kidney")) +
    theme_custom(plot_top_margin=0, base_size=22) +
    scale_y_continuous(labels=function(x){paste0(x*100, "%")}) +
    labs(x="Year", y="Percentage of cases")
cowplot::plot_grid(n, pct, ncol=1)
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2025-04-28.pdf", width=15, height=12)
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2025-04-28.png", width=15, height=12)

```

```{r}
data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_year_counts.csv")
icd_data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_icd_n_diags_2025-04-29.csv")
data <- data %>% dplyr::left_join(icd_data, by="YEAR")
data <- data %>%  
  dplyr::filter(ICD_AFTER==1, EXCLUDE==1, DIFF==30) %>% 
  dplyr::select(YEAR, N_CASE_ICD, N_CASE, N_CONTROL, N_MEAN_ABNORMAL, N_MEAN_NORMAL, N_MAX_ABNORMAL, N_MAX_NORMAL) %>%
  pivot_longer(c("N_CASE",  "N_CASE_ICD", "N_CONTROL", "N_MEAN_ABNORMAL", "N_MEAN_NORMAL", "N_MAX_ABNORMAL", "N_MAX_NORMAL")) %>%
  dplyr::mutate(TYPE=dplyr::case_when(name=="N_CASE" ~ "Diagnosis (30 days)",
                              name=="N_CONTROL" ~ "Diagnosis (30 days)",
                              name=="N_CONTROL" ~ "Diagnosis (30 days)",
                              name=="N_CASE_ICD" ~ "Diagnosis (ICD+ATC)",
                              name=="N_MEAN_ABNORMAL" ~ "Mean abnormal",
                              name=="N_MAX_ABNORMAL" ~ "Max abnormal",
                              name=="N_MAX_NORMAL" ~ "Max abnormal",
                              name=="N_MEAN_NORMAL" ~ "Mean abnormal")) %>%
  dplyr::mutate(STATUS=dplyr::case_when(name=="N_CASE" ~ "Case",
                              name=="N_CONTROL" ~ "Control",
                              name=="N_CASE_ICD" ~ "Case",
                              name=="N_MEAN_ABNORMAL" ~ "Case",
                              name=="N_MEAN_NORMAL" ~ "Control",
                              name=="N_MAX_ABNORMAL"~"Case",
                              name=="N_MAX_NORMAL"~"Control")) %>%
  dplyr::select(-name) %>%
  pivot_wider(names_from=STATUS, values_from=value)

data$TYPE <- factor(data$TYPE, levels=c("Diagnosis (ICD+ATC)", "Max abnormal", "Mean abnormal", "Diagnosis (30 days)" ))
data
pct <- ggplot(data, aes(x=YEAR, y=Case, fill=as.factor(TYPE))) +
    geom_ribbon(aes(ymin=0, ymax=Case), alpha=1) +
    scale_fill_manual(values=c(custom_colors_brewer_sorted(5)[5],custom_colors_brewer_sorted(4)[1], custom_colors_brewer_sorted(5)[2], custom_colors_brewer_sorted(4)[3] )) +
    theme_custom(plot_top_margin=0, base_size=22) +
    guides(fill= guide_legend(nrow=2, reverse=TRUE)) +
    scale_y_continuous(labels=so_formatter, limits=c(0,3300)) +
    labs(x="Year", y="Number of cases")
pct
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2_all_2025-04-29.png", width=10, height=7)

pct <- ggplot(data %>% dplyr::filter(TYPE=="Diagnosis (ICD+ATC)"), aes(x=YEAR, y=Case, fill=as.factor(TYPE))) +
    geom_ribbon(aes(ymin=0, ymax=Case), alpha=1.0) +
    scale_fill_manual(values=c(custom_colors_brewer_sorted(5)[5])) +
    theme_custom(plot_top_margin=0, base_size=22) +
    guides(fill= guide_legend(nrow=2, reverse=TRUE)) +
    scale_y_continuous(labels=so_formatter, limits=c(0,3300)) +
    labs(x="Year", y="Number of cases")
pct
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2_icd_2025-04-29.png", width=10, height=7)

pct <- ggplot(data %>% dplyr::filter(TYPE%in%c("Diagnosis (ICD+ATC)", "Diagnosis (30 days)")), aes(x=YEAR, y=Case, fill=as.factor(TYPE))) +
    geom_ribbon(aes(ymin=0, ymax=Case), alpha=1.0) +
    scale_fill_manual(values=c(custom_colors_brewer_sorted(5)[5], custom_colors_brewer_sorted(4)[3])) +
    theme_custom(plot_top_margin=0, base_size=22) +
    guides(fill= guide_legend(nrow=2, reverse=TRUE)) +
    scale_y_continuous(labels=so_formatter, limits=c(0,3300)) +
    labs(x="Year", y="Number of cases")
pct
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2_icd-diag30_2025-04-29.png", width=10, height=7)


pct <- ggplot(data %>% dplyr::filter(TYPE%in%c("Diagnosis (ICD+ATC)", "Diagnosis (30 days)", "Mean abnormal")), aes(x=YEAR, y=Case, fill=as.factor(TYPE))) +
    geom_ribbon(aes(ymin=0, ymax=Case), alpha=1.0) +
    scale_fill_manual(values=c(custom_colors_brewer_sorted(5)[5],custom_colors_brewer_sorted(5)[2], custom_colors_brewer_sorted(4)[3] )) +
    theme_custom(plot_top_margin=0, base_size=22) +
    guides(fill= guide_legend(nrow=2, reverse=TRUE)) +
    scale_y_continuous(labels=so_formatter, limits=c(0,3300)) +
    labs(x="Year", y="Number of cases")
pct
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2_icd-diag30-mean_2025-04-29.png", width=10, height=7)


```
```{r}
ata <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_year_counts.csv")
icd_data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_icd_n_diags_2025-04-29.csv")
data <- data %>% dplyr::left_join(icd_data, by="YEAR")
data <- data %>%  
  dplyr::filter(ICD_AFTER==1, EXCLUDE==1, DIFF==30) %>% 
  dplyr::select(YEAR, N_CASE_ICD, N_CASE, N_CONTROL, N_MEAN_ABNORMAL, N_MEAN_NORMAL, N_MAX_ABNORMAL, N_MAX_NORMAL) %>%
  pivot_longer(c("N_CASE",  "N_CASE_ICD", "N_CONTROL", "N_MEAN_ABNORMAL", "N_MEAN_NORMAL", "N_MAX_ABNORMAL", "N_MAX_NORMAL")) %>%
  dplyr::mutate(TYPE=dplyr::case_when(name=="N_CASE" ~ "Diagnosis (30 days)",
                              name=="N_CONTROL" ~ "Diagnosis (30 days)",
                              name=="N_CONTROL" ~ "Diagnosis (30 days)",
                              name=="N_CASE_ICD" ~ "Diagnosis (ICD+ATC)",
                              name=="N_MEAN_ABNORMAL" ~ "Mean abnormal",
                              name=="N_MAX_ABNORMAL" ~ "Max abnormal",
                              name=="N_MAX_NORMAL" ~ "Max abnormal",
                              name=="N_MEAN_NORMAL" ~ "Mean abnormal")) %>%
  dplyr::mutate(STATUS=dplyr::case_when(name=="N_CASE" ~ "Case",
                              name=="N_CONTROL" ~ "Control",
                              name=="N_CASE_ICD" ~ "Case",
                              name=="N_MEAN_ABNORMAL" ~ "Case",
                              name=="N_MEAN_NORMAL" ~ "Control",
                              name=="N_MAX_ABNORMAL"~"Case",
                              name=="N_MAX_NORMAL"~"Control")) %>%
  dplyr::select(-name) %>%
  pivot_wider(names_from=STATUS, values_from=value)

data$TYPE <- factor(data$TYPE, levels=c("Max abnormal", "Mean abnormal", "Diagnosis (30 days)" ))
data
pct <- ggplot(data, aes(x=YEAR, y=(Case/(Case+Control)), fill=as.factor(TYPE))) +
    geom_ribbon(aes(ymin=0, ymax=(Case/(Case+Control))), alpha=1.0) +
    scale_fill_manual(values=custom_colors_brewer_sorted(4)) +
    theme_custom(plot_top_margin=0, base_size=22) +
    guides(fill= guide_legend(nrow=2, reverse=TRUE)) +
   scale_y_continuous(labels=function(x){paste0(x*100, "%")}) +
    labs(x="Year", y="Percentage of cases")
pct

ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_pctcases_2_2025-04-29.png", width=10, height=7)

```


```{r}
data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-04-28/hba1c_year_counts.csv")

data <- data %>%  
  dplyr::filter(ICD_AFTER==1, EXCLUDE==1, DIFF==30) %>% 
  dplyr::select(YEAR, N_CASE, N_CONTROL, N_MEAN_ABNORMAL, N_MEAN_NORMAL, N_MAX_ABNORMAL, N_MAX_NORMAL) %>%
  pivot_longer(c("N_CASE", "N_CONTROL", "N_MEAN_ABNORMAL", "N_MEAN_NORMAL", "N_MAX_ABNORMAL", "N_MAX_NORMAL")) %>%
  dplyr::mutate(TYPE=dplyr::case_when(name=="N_CASE" ~ "Diagnosis",
                              name=="N_CONTROL" ~ "Diagnosis",
                              name=="N_MEAN_ABNORMAL" ~ "Mean abnormal",
                              name=="N_MAX_ABNORMAL" ~ "Max normal",
                              name=="N_MAX_NORMAL" ~ "Max normal",
                              name=="N_MEAN_NORMAL" ~ "Mean abnormal")) %>%
  dplyr::mutate(STATUS=dplyr::case_when(name=="N_CASE" ~ "Case",
                              name=="N_CONTROL" ~ "Control",
                              name=="N_MEAN_ABNORMAL" ~ "Case",
                              name=="N_MEAN_NORMAL" ~ "Control",
                              name=="N_MAX_ABNORMAL"~"Case",
                              name=="N_MAX_NORMAL"~"Control")) %>%
  dplyr::select(-name) %>%
  pivot_wider(names_from=STATUS, values_from=value)

pct <- ggplot(data, aes(x=YEAR, y=(Case/(Case+Control)))) +
    geom_line(size=1, aes(color=as.factor(TYPE))) +
    scale_color_manual(values=custom_colors_brewer_sorted(3), labels=c("Data-based diagnosis", "Mean abnormal", "Max abnormal")) +
    theme_custom(plot_top_margin=0, base_size=22) +
    scale_y_continuous(labels=function(x){paste0(x*100, "%")}) +
    labs(x="Year", y="Percentage of cases")
pct
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/hba1c_ncases_2_2025-04-28.png", width=10, height=7)

```
```{r}
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c("#29557B",   "#748AAA", "#EAB034", "#FBCF9D",   "#588986", "#D5694F",  "#CCB6AF","#7BA05B","#7D7C7F",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}

so_formatter <- function(x) {
  dplyr::case_when(
      x < 1e3 ~ as.character(x),
      x < 1e6 ~ paste0(as.character(x/1e3), "K"),
      x < 1e9 ~ paste0(as.character(x/1e6), "M"),
      TRUE ~ "To be implemented..."
  )
}


#' Custom color selection 
#' 
#' Based on https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=10
#' 
#' @param N_colors The number of colors
#' 
#' @author Kira E. Detrois
#' 
#' @export 
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c( "#29557B",   "#748AAA",   "#7D7C7F", "#CCB6AF", "#588986", "#D5694F","#7BA05B","#FBCF9D", "#EAB034",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}
##################### THEMES ####################
theme_custom <- function(base_size = 18,
                      legend_pos = "bottom",
                      plot_top_margin = -30,
                      axis_x_bottom_margin=0,
                      axis_y_left_margin=0,
                      legend_box_spacing=1,
                      line_size=1.5) {
    ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      text=ggplot2::element_text(colour="black"),
      # Titles
      plot.title=ggplot2::element_text(hjust=0, margin=margin(t=plot_top_margin, b=5), size=base_size),
      plot.subtitle=ggplot2::element_text(hjust=0, size=base_size*0.9,  margin=margin(t=plot_top_margin, b=5), face="bold"),
      plot.caption=ggplot2::element_text(size=base_size*0.6, hjust=0, margin=margin(t=10)),
      # Facet grid / wrap titles
      strip.text = ggplot2::element_text(hjust=0, face="bold", size=base_size*0.8, margin=margin(b=5)),
      # Legend
      legend.title=ggplot2::element_blank(),
      legend.position = legend_pos,
      legend.text=ggplot2::element_text(size=base_size*0.8),
      legend.key.spacing.y=grid::unit(0.5, "lines"),
      legend.margin = ggplot2::margin(legend_box_spacing, legend_box_spacing, legend_box_spacing, legend_box_spacing),
      # Axes
      axis.title=ggplot2::element_text(size=base_size*0.8),
      axis.text = ggplot2::element_text(size=base_size*0.75),
      axis.title.x = ggplot2::element_text(margin=margin(t=5, b=axis_x_bottom_margin)),
      axis.title.y = ggplot2::element_text(margin=margin(r=5), l=axis_y_left_margin, angle=90),
      # Other settings
      panel.border = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(colour=NA, fill=NA),
      # Grid settings
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.x =  ggplot2::element_line(colour="grey50", linewidth=line_size-0.75*line_size, linetype=2),
      panel.grid.major.y = ggplot2::element_line(colour="grey50", linewidth=line_size-0.5*line_size, linetype=2),
      panel.grid.minor.y = ggplot2::element_line(colour = "grey50", linewidth=line_size-0.75*line_size, linetype=2),
    )
}

```
