```{r}
library(tidyverse)
pred_colors <- c(PGS1="#D5694F", PGS2="#EAB034", Registry="#CCB6AF", Age="#9BB59B", Sex="#29557B", eGFR="#748AAA")

```

```{r}
data <- readr::read_delim("/home/kira/Dokumente/DSGE/projects/VALID/results/data/2025-10-10/OR_2025-10-10.tsv")
data
```

```{r}
ggplot(data %>% filter(MODEL=="Full"), aes(y=reorder(PREDICT, OR), x=OR, fill=PREDICT)) +
    geom_vline(xintercept=1, size=1.25) +
    geom_bar(stat="identity") +
    geom_text(aes(label=OR), hjust=-0.5, size=8) +
    facet_wrap(~ SET, ncol=2, scales = "free_y") +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    # x-limit 1-2.5 without bars vanishing
    coord_cartesian(xlim=c(1, 3)) +
    # add extra line at 1
    # add vertical line at 1
    scale_fill_manual(values = pred_colors, guide="none") +
    theme_custom(base_size=32) 
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/full_model_ors.png"),  
        width = 25, height = 10, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/full_model_ors.pdf"),  
        width = 25, height = 10, dpi = 300, bg = "white")

```



```{r}
ggplot(data %>% filter(MODEL=="pgs"), aes(y=reorder(PREDICT, OR), x=OR, fill=PREDICT)) +
    geom_vline(xintercept=1, size=1.25) +
    geom_bar(stat="identity") +
    geom_text(aes(label=OR), hjust=-0.5, size=8) +
    facet_wrap(~ SET, ncol=2, scales = "free_y") +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    # x-limit 1-2.5 without bars vanishing
    coord_cartesian(xlim=c(1, 5.2)) +
    # add extra line at 1
    # add vertical line at 1
    scale_fill_manual(values = pred_colors, guide="none") +
    theme_custom(base_size=32) 
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/pgs_model_ors.png"),  
        width = 25, height = 10, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/pgs_model_ors.pdf"),  
        width = 25, height = 10, dpi = 300, bg = "white")

```



```{r}
ggplot(data %>% filter(MODEL=="egfr_pgs"), aes(y=reorder(PREDICT, OR), x=OR, fill=PREDICT)) +
    geom_vline(xintercept=1, size=1.25) +
    geom_bar(stat="identity") +
    geom_text(aes(label=OR), hjust=-0.5, size=8) +
    facet_wrap(~ SET, ncol=2, scales = "free_y") +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    # x-limit 1-2.5 without bars vanishing
    coord_cartesian(xlim=c(1, 5.2)) +
    # add extra line at 1
    # add vertical line at 1
    scale_fill_manual(values = pred_colors, guide="none") +
    theme_custom(base_size=32) 
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/egfr_pgs_model_ors.png"),  
        width = 25, height = 10, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/egfr_pgs_model_ors.pdf"),  
        width = 25, height = 10, dpi = 300, bg = "white")

```

### No aucs_no_history

```{r}
ggplot(data %>% filter(MODEL=="pgs_nh"), aes(y=reorder(PREDICT, OR), x=OR, fill=PREDICT)) +
    geom_vline(xintercept=1, size=1.25) +
    geom_bar(stat="identity") +
    geom_text(aes(label=OR), hjust=-0.5, size=8) +
    facet_wrap(~ SET, ncol=2, scales = "free_y") +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    # x-limit 1-2.5 without bars vanishing
    coord_cartesian(xlim=c(1, 7)) +
    # add extra line at 1
    # add vertical line at 1
    scale_fill_manual(values = pred_colors, guide="none") +
    theme_custom(base_size=32) 
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/pgs_model_nh_ors.png"),  
        width = 25, height = 10, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/pgs_model_nh_ors.pdf"),  
        width = 25, height = 10, dpi = 300, bg = "white")

```


```{r}
mdl_colors <- c(`Age+sex`="#EAB034", `Full model`="#9BB59B", `Full+PGS model`="#588986", `PGS model`="#D5694F", `eGFR+PGS model`="#29557B", "eGFR model"="#748AAA")
pred_colors <- c(PGS1="#D5694F", PGS2="#EAB034", Registry="#CCB6AF", Age="#9BB59B", Sex="#29557B", eGFR="#748AAA")

aucs <- tibble(
    MODEL = c("Age+sex", "Age+sex", "Full model", "Full model", "Full+PGS model", "Full+PGS model", "PGS model", "PGS model", "eGFR+PGS model", "eGFR+PGS model", "eGFR model", "eGFR model"),
    SET = c("Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test"),
    AUC_P = c(0.7742, 0.7723, 0.91, 0.89, 0.92, 0.89, 0.7916, 0.784, 0.87, 0.858, 0.87, 0.854),
    AUC_P_CIneg = c(0.76, 0.747, 0.9, 0.87, 0.91, 0.87, 0.78, 0.76, 0.86, 0.833, 0.86, 0.829),
    AUC_P_CIpos = c(0.787, 0.796, 0.92, 0.912, 0.93, 0.91, 0.8, 0.81, 0.88, 0.884, 0.88, 0.88),

)
```

```{r}
options(vsc.plot = TRUE)
ggplot(aucs, aes(y=reorder(MODEL, AUC_P), x=AUC_P, color=MODEL)) +
    geom_vline(xintercept=0.5, size=1.25) +

    # CI bars
    geom_errorbarh(aes(xmin=AUC_P_CIneg, xmax=AUC_P_CIpos), height=0.1, size=1) +
    geom_point(size=5) +
    #geom_text(aes(label=OR), hjust=-0.5, size=8) +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    coord_cartesian(xlim=c(0.5, 1.0)) +
    facet_wrap(~ SET, ncol=2) +
    # x-limit 1-2.5 without bars vanishing
    # add extra line at 1
    # add vertical line at 1
    scale_color_manual(values = mdl_colors, guide="none") +
    theme_custom(base_size=32) 

ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_all.pdf"),  
        width = 22, height = 7, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_all.png"),  
        width = 22, height = 7, dpi = 300, bg = "white")
```



```{r}
mdl_colors <- c(`Age+sex`="#EAB034", `Full model`="#9BB59B", `PGS model`="#D5694F", `eGFR+PGS model`="#29557B")
pred_colors <- c(PGS1="#D5694F", PGS2="#EAB034", Registry="#CCB6AF", Age="#9BB59B", Sex="#29557B", eGFR="#748AAA")

aucs_nohistorys <- tibble(
    MODEL = c("Age+sex", "Age+sex", "Full model", "Full model", "PGS model", "PGS model", "eGFR+PGS model", "eGFR+PGS model"),
    SET = c("Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test"),
    AUC_P = c(0.787, 0.87, 0.83, 0.86, 0.8, 0.86, 0.77, 0.86),
    AUC_P_CIneg = c(0.723, 0.79, 0.78, 0.75, 0.74, 0.75, 0.71, 0.77),
    AUC_P_CIpos = c(0.835, 0.94, 0.88, 0.95, 0.86, 0.95, 0.82, 0.93 ),

)
```

```{r}
options(vsc.plot = TRUE)
ggplot(aucs_nohistorys, aes(y=reorder(MODEL, AUC_P), x=AUC_P, color=MODEL)) +
    geom_vline(xintercept=0.5, size=1.25) +

    # CI bars
    geom_errorbarh(aes(xmin=AUC_P_CIneg, xmax=AUC_P_CIpos), height=0.1, size=1) +
    geom_point(size=5) +
    #geom_text(aes(label=OR), hjust=-0.5, size=8) +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    coord_cartesian(xlim=c(0.5, 1.0)) +
    facet_wrap(~ SET, ncol=2) +
    # x-limit 1-2.5 without bars vanishing
    # add extra line at 1
    # add vertical line at 1
    scale_color_manual(values = mdl_colors, guide="none") +
    theme_custom(base_size=32) 

ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_no_history.pdf"),  
        width = 22, height = 6, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_no_history.png"),  
        width = 22, height = 6, dpi = 300, bg = "white")
```




```{r}
mdl_colors <- c(`Age+sex`="#EAB034", `Full model`="#9BB59B", `PGS model`="#D5694F", `eGFR+PGS model`="#29557B", "eGFR model"="#748AAA")
pred_colors <- c(PGS1="#D5694F", PGS2="#EAB034", Registry="#CCB6AF", Age="#9BB59B", Sex="#29557B", eGFR="#748AAA")

aucs_longhistory <- tibble(
    MODEL = c("Age+sex", "Age+sex", "Full model", "Full model", "PGS model", "PGS model", "eGFR+PGS model", "eGFR+PGS model", "eGFR model", "eGFR model"),
    SET = c("Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test", "Train", "Test"),
    AUC_P = c(0.811, 0.803, 0.9333, 0.9, 0.84, 0.817, 0.868, 0.827, 0.862, 0.82),
    AUC_P_CIneg = c(0.776, 0.743, 0.917, 0.85, 0.806, 0.772, 0.828, 0.754, 0.819, 0.742),
    AUC_P_CIpos = c(0.84, 0.848, 0.95, 0.949, 0.873, 0.859, 0.9, 0.891, 0.895, 0.885),

)
```

```{r}
options(vsc.plot = TRUE)
ggplot(aucs_longhistory, aes(y=reorder(MODEL, AUC_P), x=AUC_P, color=MODEL)) +
    geom_vline(xintercept=0.5, size=1.25) +

    # CI bars
    geom_errorbarh(aes(xmin=AUC_P_CIneg, xmax=AUC_P_CIpos), height=0.1, size=1) +
    geom_point(size=5) +
    #geom_text(aes(label=OR), hjust=-0.5, size=8) +
    labs(title = "",
          x = "Odds Ratio",
          y = "") +
    coord_cartesian(xlim=c(0.5, 1.0)) +
    facet_wrap(~ SET, ncol=2) +
    # x-limit 1-2.5 without bars vanishing
    # add extra line at 1
    # add vertical line at 1
    scale_color_manual(values = mdl_colors, guide="none") +
    theme_custom(base_size=32) 

ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_long_history.pdf"),  
        width = 22, height = 6, dpi = 300, bg = "white")
ggsave(paste0("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/", Sys.Date(), "/aucs_long_history.png"),  
        width = 22, height = 6, dpi = 300, bg = "white")
```




```{r}
so_formatter <- function(x) {
  dplyr::case_when(
      x < 1e3 ~ as.character(x),
      x < 1e6 ~ paste0(as.character(x/1e3), "K"),
      x < 1e9 ~ paste0(as.character(x/1e6), "M"),
      TRUE ~ "To be implemented..."
  )
}


#' Custom color selection 
#' 
#' Based on https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=10
#' 
#' @param N_colors The number of colors
#' 
#' @author Kira E. Detrois
#' 
#' @export 
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c( "#29557B",   "#748AAA",   "#7D7C7F", "#CCB6AF", "#588986", "#D5694F","#7BA05B","#FBCF9D", "#EAB034",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}

##################### THEMES ####################
theme_custom <- function(base_size = 18,
                      legend_pos = "bottom",
                      plot_top_margin = -30,
                      axis_x_bottom_margin=0,
                      axis_y_left_margin=0,
                      legend_box_spacing=1,
                      line_size=1.5) {
    ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      text=ggplot2::element_text(colour="black", family="sans"),
      # Titles
      plot.title=ggplot2::element_text(hjust=0, margin=margin(t=plot_top_margin, b=5), size=base_size),
      plot.subtitle=ggplot2::element_text(hjust=0, size=base_size*0.9,  margin=margin(t=plot_top_margin, b=5), face="bold"),
      plot.caption=ggplot2::element_text(size=base_size*0.6, hjust=0, margin=margin(t=10)),
      # Facet grid / wrap titles
      strip.text = ggplot2::element_text(hjust=0, face="bold", size=base_size*0.8, margin=margin(b=5)),
      # Legend
      legend.title=ggplot2::element_blank(),
      legend.position = legend_pos,
      legend.text=ggplot2::element_text(size=base_size*0.8),
      legend.key.spacing.y=grid::unit(0.5, "lines"),
      legend.margin = ggplot2::margin(legend_box_spacing, legend_box_spacing, legend_box_spacing, legend_box_spacing),
      # Axes
      axis.title=ggplot2::element_text(size=base_size*0.8),
      axis.text = ggplot2::element_text(size=base_size*0.75),
      axis.title.x = ggplot2::element_text(margin=margin(t=5, b=axis_x_bottom_margin)),
      axis.title.y = ggplot2::element_text(margin=margin(r=5), l=axis_y_left_margin, angle=90),
      # Other settings
      panel.border = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(colour=NA, fill=NA),
      # Grid settings
      panel.grid.minor.y = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_line(colour="grey75", linewidth=line_size-0.5*line_size, linetype=2),
      panel.grid.minor.x = ggplot2::element_blank(),
    )
}

```
