```{r}
library(readr)
library(ggplot2)
library(dplyr)
```

```{r}
data <- tibble::tibble(
          YEAR=2014:2023,
          CASES=c(35.32, 34.67, 32.74, 28.67, 21.85, 15.66, 10.09, 8.82, 6.19, 4.030),
          CONTROLS=c(19.16, 19.13, 18.97, 18.59, 17.57, 16.08, 14.3, 12.58, 10.14, 7.25)
)
data <- tidyr::pivot_longer(data, cols=c("CASES", "CONTROLS"), names_to="GROUP", values_to="PCT")
data
```

```{r}
library(ggplot2)
ggplot2::ggplot(data, aes(x=YEAR, y=PCT, color=GROUP)) +
    geom_point(size=3) +
    geom_line(size=1) +
    theme_custom(plot_top_margin=0) +
    scale_color_manual(values=custom_colors_brewer_sorted(2), labels=c("Cases", "Controls")) +
    labs(y="Proportion of individuals (%)", x="Year", fill="", title="Percentage of individuals missing eGFR history") +
    scale_x_continuous(breaks=seq(2014, 2023, 1), labels=seq(2014, 2023, 1))

ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_cases_controls_missing_history_pct_2024-10-11.pdf", width=10, height=7, dpi=300)
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_cases_controls_missing_history_pct_2024-10-11.png", width=10, height=7, dpi=300)

``` 

```{r}
data <- tibble::tibble(
          YEAR=2014:2023,
          N_CASES=c(3409, 3375, 3271, 3031, 2650, 2242, 1754, 1355, 808, 273),
          N_ABNORM=c(15538, 15503, 15390, 15130, 14686, 14186, 13480, 12772, 11644, 9793),
          PCT_CASES=c(1.45, 1.44, 1.4, 1.3, 1.16, 1.01, 0.82, 0.67, 0.46, 0.21),
          PCT_ABNORM=c(6.54, 6.53, 6.5, 6.43, 6.34, 6.3, 6.24, 6.27, 6.49, 7.29)
)
data <- tidyr::pivot_longer(data, cols=c("PCT_CASES", "PCT_ABNORM"), names_to="GROUP", values_to="N")
data
```

```{r}
library(ggplot2)
ggplot2::ggplot(data, aes(x=YEAR, y=N, color=GROUP)) +
    geom_point(size=3) +
    geom_line(size=1) +
    theme_custom(plot_top_margin=0) +
    scale_color_manual(values=custom_colors_brewer_sorted(2), labels=c("Any abnormal", "Cases")) +
    labs(y="Percentage of cases", x="Year", fill="", title="Percentage of cases depending on the minimum year of diagnosis") +
    scale_x_continuous(breaks=seq(2014, 2023, 1), labels=seq(2014, 2023, 1))

ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_case_pct_different_year_cutofs_2025-04-08.pdf", width=10, height=7, dpi=300)
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_case_pct_different_year_cutofs_2025-04-08.png", width=10, height=7, dpi=300)
``` 


```{r}
data <- tibble::tibble(
          YEAR=2014:2023,
          N_CASES=c(3409, 3375, 3271, 3031, 2650, 2242, 1754, 1355, 808, 273),
          N_ABNORM=c(15538, 15503, 15390, 15130, 14686, 14186, 13480, 12772, 11644, 9793),
          PCT_CASES=c(1.45, 1.44, 1.4, 1.3, 1.16, 1.01, 0.82, 0.67, 0.46, 0.21),
          PCT_ABNORM=c(6.54, 6.53, 6.5, 6.43, 6.34, 6.3, 6.24, 6.27, 6.49, 7.29)
)
data <- tidyr::pivot_longer(data, cols=c("N_CASES", "N_ABNORM"), names_to="GROUP", values_to="N")
data
```

```{r}
library(ggplot2)
ggplot2::ggplot(data, aes(x=YEAR, y=N, color=GROUP)) +
    geom_point(size=3) +
    geom_line(size=1) +
    theme_custom(plot_top_margin=0) +
    scale_color_manual(values=custom_colors_brewer_sorted(2), labels=c("Any abnormal", "Cases")) +
    labs(y="Percentage of cases", x="Year", fill="", title="Percentage of cases depending on the minimum year of diagnosis") +
    scale_x_continuous(breaks=seq(2014, 2023, 1), labels=seq(2014, 2023, 1))

ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_n_case_different_year_cutofs_2025-04-08.pdf", width=10, height=7, dpi=300)
ggsave("/home/kira/Dokumente/DSGE/projects/VALID/results/plots/valid_n_case_different_year_cutofs_2025-04-08.png", width=10, height=7, dpi=300)
``` 


```{r}
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c("#29557B",   "#748AAA", "#EAB034", "#FBCF9D",   "#588986", "#D5694F",  "#CCB6AF","#7BA05B","#7D7C7F",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}

so_formatter <- function(x) {
  dplyr::case_when(
      x < 1e3 ~ as.character(x),
      x < 1e6 ~ paste0(as.character(x/1e3), "K"),
      x < 1e9 ~ paste0(as.character(x/1e6), "M"),
      TRUE ~ "To be implemented..."
  )
}


#' Custom color selection 
#' 
#' Based on https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=10
#' 
#' @param N_colors The number of colors
#' 
#' @author Kira E. Detrois
#' 
#' @export 
custom_colors_brewer_sorted <- function(N_colors) {
    if(N_colors == 1)
      c("#000000")
    else if(N_colors == 2) {
      c("#D5694F", "#29557B")
    } else if(N_colors == 3)  {
      c("#D5694F", "#29557B", "#EAB034")
    } else if(N_colors == 4) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA")
    } else if(N_colors == 5) {
      c("#D5694F", "#29557B", "#EAB034", "#748AAA", "#CCB6AF")
    } else if(N_colors == 10) {
      c( "#29557B",   "#748AAA",   "#7D7C7F", "#CCB6AF", "#588986", "#D5694F","#7BA05B","#FBCF9D", "#EAB034",  "#841C26")
    } else if(N_colors == 17) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#59260B", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6")
    } else if(N_colors == 18) {
      c("#841C26", "#B53389", "#C6878F", "#A81C07", "#D5694F", "#FBCF9D", "#FBCF9D", "#CCB6AF", "#7D7C7F", "#91A3B0",
         "#3C4E2D", "#7BA05B", "#9BB59B", "#588986","#29557B","#748AAA", "#ADD8E6", "#D6ECFF")
    }
}
##################### THEMES ####################
theme_custom <- function(base_size = 18,
                      legend_pos = "bottom",
                      plot_top_margin = -30,
                      axis_x_bottom_margin=0,
                      axis_y_left_margin=0,
                      legend_box_spacing=1,
                      line_size=1.5) {
    ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      text=ggplot2::element_text(colour="black"),
      # Titles
      plot.title=ggplot2::element_text(hjust=0, margin=margin(t=plot_top_margin, b=5), size=base_size),
      plot.subtitle=ggplot2::element_text(hjust=0, size=base_size*0.9,  margin=margin(t=plot_top_margin, b=5), face="bold"),
      plot.caption=ggplot2::element_text(size=base_size*0.6, hjust=0, margin=margin(t=10)),
      # Facet grid / wrap titles
      strip.text = ggplot2::element_text(hjust=0, face="bold", size=base_size*0.8, margin=margin(b=5)),
      # Legend
      legend.title=ggplot2::element_blank(),
      legend.position = legend_pos,
      legend.text=ggplot2::element_text(size=base_size*0.8),
      legend.key.spacing.y=grid::unit(0.5, "lines"),
      legend.margin = ggplot2::margin(legend_box_spacing, legend_box_spacing, legend_box_spacing, legend_box_spacing),
      # Axes
      axis.title=ggplot2::element_text(size=base_size*0.8),
      axis.text = ggplot2::element_text(size=base_size*0.75),
      axis.title.x = ggplot2::element_text(margin=margin(t=5, b=axis_x_bottom_margin)),
      axis.title.y = ggplot2::element_text(margin=margin(r=5), l=axis_y_left_margin, angle=90),
      # Other settings
      panel.border = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(colour=NA, fill=NA),
      # Grid settings
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.x =  ggplot2::element_line(colour="grey50", linewidth=line_size-0.75*line_size, linetype=2),
      panel.grid.major.y = ggplot2::element_line(colour="grey50", linewidth=line_size-0.5*line_size, linetype=2),
      panel.grid.minor.y = ggplot2::element_line(colour = "grey50", linewidth=line_size-0.75*line_size, linetype=2),
    )
}

```
